### ISSUE TITLE
Request: Only add PR comment in case of a failure

### ISSUE THREAD

**Issue by armsnyder** [bufbuild/buf-action#82]
To reduce noise on PRs, we would like if the action only added the PR comment in the case of one of the checks failing. I suggest a new action input like `skip_pr_comment_on_success`. Alternatively, output the comment markdown as an action output and let the user decide how to handle it.

**Comment by nicksnyder** [comment]
Is disabling the PR comment completely by setting `pr_comment: false` not sufficient to solve the noise problem you have? (The action would still report the check status and annotate the difference with lint/braking errors).

Can think about this. If we do it, I would want to avoid adding another config option, but we might be able to turn pr_comment from book to more of an enum.

**Comment by armsnyder** [comment]
Hi @nicksnyder! 👋 Thanks for the quick response. If setting `pr_comment: false` still keeps the job step summary, then that's good enough for me. I'll close this for now. 😄
